[package]
name = "wayland_client"
version = "0.1.0"
edition = "2024"

[lib]
name = "wayland_client"
crate-type = ["dylib"]

[dependencies]
rustler = "0.36.2"
wayland-client = "0.31.11"
wayland-protocols = "0.32.9"
wayland-sys = "0.31.7"

[dependencies.rustler_sys]
version = "2.4.3"
optional = true
