name: Copilot Setup Steps

"on":
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  copilot-setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Verify devShell environment and dependencies
        run: |
          echo "=== Entering devShell and verifying dependencies ==="
          nix develop --command bash -c "
            echo 'Current shell: $0'
            echo
            echo '=== Checking Elixir dependencies ==='
            which elixir && echo 'Elixir found' || echo 'ERROR: Elixir not found'
            which mix && echo 'Mix found' || echo 'ERROR: Mix not found'  
            which hex && echo 'Hex found' || echo 'ERROR: Hex not found'
            which rebar3 && echo 'Rebar3 found' || echo 'ERROR: Rebar3 not found'
            echo
            echo '=== Checking Rust dependencies ==='
            which cargo && echo 'Cargo found' || echo 'ERROR: Cargo not found'
            which rustc && echo 'Rustc found' || echo 'ERROR: Rustc not found'
            echo
            echo '=== Version information ==='
            echo 'Elixir version:'
            elixir --version
            echo
            echo 'Rust version:'
            rustc --version
            echo 'Cargo version:'
            cargo --version
            echo
            echo '=== DevShell environment ready for Copilot operations ==='
          "

      - name: Test Elixir project setup in devShell
        run: |
          nix develop --command bash -c "
            echo '=== Testing Elixir project setup ==='
            mix deps.get
            mix compile
            echo 'Elixir project compiled successfully'
          "

      - name: Test Rust project setup in devShell  
        run: |
          nix develop --command bash -c "
            echo '=== Testing Rust project setup ==='
            cd native/wayland_client
            cargo check
            echo 'Rust project checked successfully'
          "

      - name: Verify Copilot Agent Environment
        run: |
          nix develop --command bash -c "
            echo '=== GitHub Copilot Agent Environment Verification ==='
            echo 'This step verifies that Copilot agents can access all required tools'
            echo 'within the devShell environment.'
            echo
            echo 'Tool paths (for Copilot agent reference):'
            echo '- Elixir: $(which elixir)'
            echo '- Mix: $(which mix)'
            echo '- Hex: $(which hex)'
            echo '- Rebar3: $(which rebar3)'
            echo '- Cargo: $(which cargo)'
            echo '- Rustc: $(which rustc)'
            echo
            echo 'Environment variables available to Copilot agents:'
            echo '- ERL_AFLAGS: $ERL_AFLAGS'
            echo '- PATH includes: $(echo \$PATH | tr ':' '\n' | grep nix | head -3)'
            echo
            echo 'Copilot agents can now:'
            echo '1. Run Elixir commands: mix, elixir, hex, rebar3'
            echo '2. Run Rust commands: cargo, rustc'
            echo '3. Access all project dependencies'
            echo '4. Execute within the consistent devShell environment'
            echo
            echo '✓ DevShell environment ready for GitHub Copilot operations!'
          "